added login component, edited app.js and button.js
BesoBerdzenishvili/meals-app pull request #16
Opened 2022-09-07 09:56 UTC by BesoBerdzenishvili

We are adding a Login.js component on '/login' path. Component allows users to sign in into their account.

component sends POST request to server on 'api/login' path, where entered userName and password will be checked.

In case of error, error message will be displayed on upper part of form field.

Button component has Id: '#loginBtn' added, which helps to create space between registration and login buttons, with margin property.

2022-09-07 20:41 UTC, ggogobera commented
Avoid adding IDs (#) to elements

2022-09-07 20:43 UTC, ggogobera requested changes

2022-09-07 20:43 UTC, ggogobera commented on src/App.js
>  import {Routes, Route} from 'react-router-dom'
Pkgs from `node_modules` should got top.

Relative imports ('../../../x) should go after `node_modules`. It's more organized

2022-09-07 20:43 UTC, ggogobera commented on src/components/pages/Login.js
> +      }
try catch?

2022-09-07 20:43 UTC, ggogobera commented on src/components/pages/Login.js
> +          <Button variant="primary" id="loginBtn">
Is there any reason you added ID to this button?

2022-09-07 20:43 UTC, ggogobera commented on src/components/pages/SignUp.js
> +          <Button variant="alert" id="loginBtn">
Ditto

2022-09-07 20:43 UTC, ggogobera commented on src/components/reusables/Button.js
> +        '&#loginBtn': {
Style by className

2022-09-08 06:27 UTC, BesoBerdzenishvili commented on src/components/pages/Login.js
> +          <Button variant="primary" id="loginBtn">
To have a space between "registration" and "login" buttons (with margin property)

2022-09-08 06:35 UTC, BesoBerdzenishvili commented on src/components/reusables/Button.js
> +        '&#loginBtn': {
Class didn't have enought specificity. Is that not a reason for using id?

2022-09-08 06:49 UTC, BesoBerdzenishvili commented on src/components/pages/Login.js
> +      }
That's the idea.

I had a problem displaying error message from try/catch and used this instead. Not appropriate?

2022-09-09 09:36 UTC, ggogobera commented on src/components/reusables/Button.js
> +        '&#loginBtn': {
Why didn't it have enough specificity? What was overriding?

Using IDs is an anti-pattern. It would help if you avoided them at all costs for styling. Basically, IDs are used for page fragments.

2022-09-09 09:38 UTC, ggogobera commented on src/components/pages/Login.js
> +      }
What was the problem? I need to understand first to tell you how to fix it.

But before I even know it, I can tell you that without the try/catch block this code will blow app the whole application if a server didn't respond with JSON data.

Those are different things.

2022-09-09 10:01 UTC, BesoBerdzenishvili commented on src/components/pages/Login.js
> +      }
I couldn't find how to display error message (that you created on server) with try/catch so I used this approach instead.

2022-09-09 10:07 UTC, BesoBerdzenishvili commented on src/components/reusables/Button.js
> +        '&#loginBtn': {
Actually it may not be a specificity issue. Just className wasn't styling element and id was, so I thought it could be specificity issue

2022-09-09 10:14 UTC, ggogobera commented on src/components/pages/Login.js
> +      }
The try/catch shouldn't be used to display errors created on the server.

It's required to avoid uncaught errors on the client side.

`await res.json()` may blow up the app.

```js
try {
  const res = await fetch('url');

  const json = await res.json();

  if (res.ok) { // res.ok is true on 2xx status codes so it means you should have res.data
    setData(json.data);
  } else {
    setError(json.message);
  }
} catch (e) {
  setError(e?.message ?? 'Something went wrong');
}
```

2022-09-09 10:17 UTC, ggogobera commented on src/components/reusables/Button.js
> +        '&#loginBtn': {
There doesn't exist any worse thing to do than adding specific styling logic to a reusable component.

You must style this button from the parent.

Imagine how many buttons you may have in the app, are you gonna style everything here? Why did you think this was a good idea?

From parent:
```js
{
   '. buttonClassName' {
        ...
    }
}
```

2022-09-09 11:42 UTC, ggogobera commented on src/components/reusables/Button.js
> +        '&#loginBtn': {
Yeah! Good catch!

The Button component should accept `className` prop and merge it with buttonStyles.

You can use [classnames](https://www.npmjs.com/package/classnames) pkg.

2022-09-10 17:41 UTC, ggogobera requested changes

2022-09-10 17:41 UTC, ggogobera commented on src/components/reusables/Button.js
> +        '&.rightBtn': {
Dude, we've already talked about this 😂

სადაც კი გასტილვა დაგჭირდება ყველა შემთხვევას აქ ხომ არ დაამატებ.

მშობლიდან უნდა გაისტილოს ეს. სადაც ამ ღილაკს იყენებ, იქ ამ ღილაკს კლასი უნდა გადმოსცე და იმ კლასის მიხედვით მერე გაასტილო იმავე კომპონენტში

2022-09-12 11:58 UTC, ggogobera approved these changes
ამჯერად ეს მუშაობს, მაგრამ 2 points:

* შეიძლება მაინც დაგჭირდეს მშობლიდან კლასის გადმოცემა ღილაკზე და მაგას არ ჰენდლავ ჯერ ღილაკში
* Box -ც შეგეძლო გამოგეყენებინა მარჯინისთვის

2022-09-12 11:59 UTC, ggogobera commented
ვიდრე დამერჯავდე ამ ბრენჩს.

როდესაც ახალ ელემენტებს ამატებ UI-ში, screenshot დაურთე ხოლმე აღწერაში, რომ ვიზუალურ მხარეზეც მოგცე ხოლმე რჩევები. ახლა მომენტარში გაუშვი ორივე ფორმის სქრინშოთი

2022-09-12 17:17 UTC, ggogobera commented
აი რა კარგია რომ დასქრინე.

დიზაინში არსებობს CTA ღილაკები (Call to Action). სხვადასხვა ღილაკს სხვადასხვა პრიორიტოტეტი აქვს და შესაბამისად სხვადასხვა დავალებას ასრულებს. 

ამ შემთხვევაში არ შეიძლება ორივე ღილაკი ერთი ფერის იყოს. CTA ღილაკებია ორივე. 

არსებობს Primary და Secondary ღილაკების ცნება, რომელიც აპლიკაციაში consistent უნდა იყოს. Primary ღილაკები იუზერს ანიშნებს რაღაც მნიშვნელოვანზე.

ამ შემთხვევაში, მაგალითად, რეგისტრაციის ფორმაში რომელი ღილაკი ასაბმიტებს ფორმას ვერ ვიგებ. თეორიულად ვიგებ, რა თქმა უნდა, მაგრამ არ არის ნათელი რა რას აკეთებს.

ღილაკები უკვე იღებენ variant პროპერტის. ორივე ფორმაში Submit ღილაკი უნდა იყოს Primary და მეორე ღილაკი Secondary. შეცვალე

2022-09-13 06:15 UTC, BesoBerdzenishvili commented
New login:
<img src='https://user-images.githubusercontent.com/76405148/189823803-1b88a9bc-c3e1-4b13-b250-88d99c97bafa.png' width='244px' />
New registration:
<img src='https://user-images.githubusercontent.com/76405148/189823811-454f8261-fb08-4d74-90f2-7a97657f9616.png' width='244px' />

2022-09-14 06:14 UTC, merged