added GuestRoute, RestrictedRoute and Login
BesoBerdzenishvili/meals-app pull request #19
Opened 2022-09-17 12:08 UTC by BesoBerdzenishvili

GuestRoute.js and RestrictedRoute.js components are added. They are protected routes;

GuestRoute checks if user is logged in, in which case it redirects user ro '/home' endpoint ('/home' is a placeholder, and will be replaced which whatever endpoint our main page will have)

RestrictedRoute checks if user is logged in, in which case it allows user to required page. else (if user is not logged in) it redirects users to '/login'

Login.js and Registration.js are wrapped inside GuestRoutes wrapper.

for determining whether user is logged in or not, isLogin.js is added. 
In isLogin.js we have:
`document.cookie = 'username=John Doe'`
which creates cookie named 'username' in Browser. This is for testing purposes and will be replaced wich cookies that will be set from server;
Next in isLogged.js we have a function 'getCookie' which gets cookie and returns it's value or nothing (if there's no cookie in Browser). Value that is returned from getCookis() will be sent to GuestRoute.js and RestrictedRoute.js (via App.js). Which getCookie's value protected routes will determine if user is logged in or not and act as described above;

2022-09-19 14:52 UTC, ggogobera requested changes
This is a wrong implementation.

- the `GuestRoute` and `PrivateRoute` components should be almost similar to the `Route` component.
- they should receive similar props as the `Route` component, e.g. `path`, `element`.
- only additional functionality it has is to check if a user is authorized and render `element` accordingly

P.S. the branch name is terrible. Why are you using pascal case + weird `_-`?

2022-09-20 09:58 UTC, ggogobera commented on src/utils/isLogin.js
> +export let isLogin = getCookie('username')
რატომ let?

ასევე, ეს უნდა იყოს ფუნქცია. როცა დავლოგაუთდები არ შეიცვლება.

export default function getSession() {
 .... cookie logic ....
}

როცა გამოვიძახებ getSession-ს უნდა მომცეს იუზერი თუ არსებობს, თუ არ არსებობს undefined იქნება.

2022-09-20 10:00 UTC, ggogobera commented
Guest და Private route კომპონენტებს შენ აწვდი იუზერს, როდესაც თვითონ უნდა დაჩეკონ იუზერი არსებობს თუ არა.

შეგიძლია AuthProvider-ში მოაქციო მთლიანი აპლიკაცია და Guest და Private route კომპონენტებმა useAuthContext-იდან ამოიღონ user, AuthProvider-მა კი user დააპროვაიდოს.

2022-09-22 12:37 UTC, ggogobera requested changes

2022-09-22 12:37 UTC, ggogobera commented on src/context/authContext.js
> +export const authContext = createContext()
https://beta.reactjs.org/apis/react/createContext#usage

Context name must be in PascalCase.

2022-09-22 12:37 UTC, ggogobera commented on src/context/authContext.js
> +import {createContext} from 'react'
This file isn't prettified.

2022-09-22 12:37 UTC, ggogobera commented on src/context/authContext.js
> +  return <authContext.Provider value={getCookie('username')}>{children}</authContext.Provider>
The value must be memoized. Better be stored in the state.

2022-09-23 11:54 UTC, ggogobera requested changes
კოდი ისევ არ არის დაფორმატებული ფრეთიერით

2022-09-23 11:54 UTC, ggogobera commented on src/context/authContext.js
> +  const [authValue, setAuthValue] = useState(getCookie('username'))
useState-ს lazy initializer ფუნქცია უნდა გადასცე, როდესაც მნიშვნელობა კონსტანტა არ არის. პირდაპირ იმპლემენტაცია დაგიწერე კომენტარში.

2022-09-23 11:54 UTC, ggogobera commented on src/context/authContext.js
> +  useMemo(() => setAuthValue(getCookie('username')), [])
useMemo-ს არასწორად იყენებ. 

1. არ არის საჭირო. useState უკვე მემოიზირებულ მნიშვნელობას გაძლევს
2. არასწორი useage არის
3. შეცდომაა იმპლემენტაციის ნაწილში

https://beta.reactjs.org/apis/react/useMemo

2022-09-23 11:55 UTC, ggogobera commented on src/context/authContext.js
> +  const [authValue, setAuthValue] = useState(getCookie('username'))
`useState(() => getCookie('username'))`

2022-09-23 13:21 UTC, BesoBerdzenishvili commented on src/context/authContext.js
> +  const [authValue, setAuthValue] = useState(getCookie('username'))
ფრეთიერს რაც შეეხება მისი დაფორმატებულია კოდი. შენთან არასწორად ხოარ ჩანს? ჩემთან ესე გამოიყურება:
![Screenshot 2022-09-23 170730](https://user-images.githubusercontent.com/76405148/191969171-8e84efce-640e-4e28-8fe2-e0d23309e8b9.png)

2022-09-23 13:33 UTC, ggogobera commented on src/context/authContext.js
> +  const [authValue, setAuthValue] = useState(getCookie('username'))
კი, PR-ში ცუდად ჩანდა. მადლობა სქრინისთვის

2022-09-23 13:34 UTC, ggogobera commented on src/context/authContext.js
> +import {createContext, useState, useMemo} from 'react'
src/context დირექტრიას src/context**s** რომ დაარქვა უკეთესი იქნება

2022-09-27 18:01 UTC, ggogobera approved these changes

2022-09-27 18:29 UTC, merged