Reusables
BesoBerdzenishvili/meals-app pull request #7
Opened 2022-07-15 10:16 UTC by BesoBerdzenishvili

added Button, Box, Input (js) reusable component to the project

2022-07-15 10:19 UTC, ggogobera commented on src/components/reusables/Input.js
> +export default function Input({variant = 'normal'}) {
წარმოიდგინე ფორმაში გაქვს ეს ელემენტი.

ვთქვათ არის username-სთვის.

და გინდა რომ username დასეტო სტეიტში. ამ კომპონენტს როგორ გამოიყენებ?

2022-07-15 10:19 UTC, ggogobera commented on src/components/reusables/Button.js
> +  as: 'button',
სჯობს პროპსების დესტრუქტურიზაციაშივე მიანიჭო as: Component = 'button'

2022-07-15 10:19 UTC, ggogobera commented on src/components/reusables/Button.js
> +export default function Button({as: Component, children, size = 'normal', variant = 'primary'}) {
თუ მინდა რომ type შევუცვალო ამ კომპონენტს submit-დან button-ზე, როგორ გავაკეთებ?

2022-07-15 10:40 UTC, BesoBerdzenishvili commented on src/components/reusables/Input.js
> +export default function Input({variant = 'normal'}) {
იშუში რომ არ ეწერა მე ვთქვი მერე მივხედავდით მაგას.

მარტივია:
type, value & onChange დავუმატებთ კომპონენტს როგორც პროპებს და ინპუტის ატრიბუტებს

2022-07-15 10:41 UTC, BesoBerdzenishvili commented on src/components/reusables/Button.js
> +export default function Button({as: Component, children, size = 'normal', variant = 'primary'}) {
აქაც ინპუტის მსგავსად type დავუმატებთ პროპად და ინპუტის ატრიბუტად

2022-07-17 10:16 UTC, ggogobera requested changes
კი ბატონო, დაუმატე ყველა კომპონენტს ის პროპსები რაც სჭირდება.

მაგრამ ყველაფერს სათითაოდ ხომ ვერ ამოიღებ, ამიტომ დანარჩენი პროპსები დასპრედე. 

სტრატეგიაა შემდეგი:
* კომპონენტს უნდა ენიჭებოდეს ყველა პროპსი რომელიც ენიჭება ექვივალენტურ DOM ელემენრტს
* და მაგის გარდა ჩვენი ლოგიკა რაც გვჭირდება, სტილი (ზომები და ა.შ.) დააექსთენდოს

2022-07-18 07:17 UTC, ggogobera requested changes

2022-07-18 07:17 UTC, ggogobera commented on src/components/reusables/Box.js
> +      {args.children}
args ცუდი სახელია, best practice არის ...props ან ...restProps.

ასევე, children-ს დესტრუქტურიზაცია ყოველთვის გქონდეს ხოლმე

2022-07-18 07:17 UTC, ggogobera commented on src/components/reusables/Box.js
> +        alignSelf: args.alignSelf,
ეს არ მითქვამს, ასე არ უნდა გააკეთო. მე გითხარი, რომ პროპსებსაც შენ იყენებ, ის უნდა დაადესტრუქტურიზო და დანარჩენი დასპრედო

2022-07-18 07:17 UTC, ggogobera commented on src/components/reusables/Input.js
> +      onChange={args.onChange}
ეს არ არის დასპრედვა. დაპსრედვა არის <input ...props />

ამ 3 პროპსის გარდა კიდევ უამრავი აქვს ინფუთს და შენი იმპლემენტაცია იმათ არ ითვალისწინებს

2022-07-18 07:22 UTC, ggogobera commented
https://beta.reactjs.org/learn/passing-props-to-a-component#forwarding-props-with-the-jsx-spread-syntax

ამონარიდი დოკუმენტაციიდან, რომელიც წაიკითხე. რატომ არ გაითვალისწინე ეს ნაწილი?

2022-07-18 08:07 UTC, BesoBerdzenishvili commented
...restProps გამოვიყენე სახელად.

რეაქტის ეგ დოკუმენტაცია არ წამიკითხვას, [ეს](https://reactjs.org/docs/components-and-props.html) წავიკითხე. მაგასაც წავიკითხავ.

2022-07-18 08:17 UTC, ggogobera commented
შეგნებულად დაგილინკე ბეტა გვერდი.

ძველი დოკუმენტაცია არ მინდოდა წაგეკითხა. ასეთ რამეებში არ უნდა გავიმაზოთ

2022-07-18 08:20 UTC, ggogobera approved these changes

2022-07-18 09:05 UTC, merged