added stitches to reusable components
BesoBerdzenishvili/meals-app pull request #9
Opened 2022-07-19 08:57 UTC by BesoBerdzenishvili

Added stitches styling to reusable components. 

We'll use same props on components, but they will be styled with stitches, which will allow us to style more effectivly by using stitches features like: thematic styling, variants, responsive styling, utilities...

2022-07-19 09:32 UTC, ggogobera requested changes
Good, good! 🚀 საერთო ჯამში კარგია, მაგრამ პატარა მნიშვნელოვანი ცვლილებები მაინც უნდა შევიტანოთ. 

ბოლომდე არ ასრულებს issue-ში მოცემულ მოთხოვნას. css უნდა გამოიყენო მაშინ, როდესაც სტატიკურად, კომპონენტს გარეთ ვერ ადეკლარირებ სტილებს და როცა დინამიურ მნიშვნელობებს იღებს სტილი, მაგალითად როგორც მარჯინი და პადინგია ბოქს კომპონენტში. დანარჩენ ადგილებში სტატიკურად უნდა დაადეკლარირო სტილები. მაგალითები კომენტარებშია

2022-07-19 09:32 UTC, ggogobera commented on src/components/reusables/Input.js
> +  const inpStyle = css({
inpStyle ცუდი სახელია. არასდროს შეამოკლო და აკრონიმები არ იხმარო სახელში

2022-07-19 09:32 UTC, ggogobera commented on src/components/reusables/Input.js
import { styled } from './wherever-you-have-stitches-config'

const StyledInput = styled('input', {
    variants: {
        variant: {
            normal: {
                width: '200px',
            },
            fluid: {
                width: '100%',
            }
        }
    }
})

2022-07-19 09:32 UTC, ggogobera commented on src/components/reusables/Input.js
> +  return <input {...restProps} className={inpStyle({variant: variant})} />
```js
<StyledInput ........>
```

2022-07-19 09:32 UTC, ggogobera commented on src/components/reusables/Button.js
> +  const btn = css({
იგივე რაც Input-ს შემთხვევაში

2022-07-19 09:32 UTC, ggogobera commented on src/components/reusables/Box.js
> +  const box = css({
აქ Input-ს მსგავსად ვერ გააკეთებდი. მაგრამ მნიშვნელოვანია რომ ამის მემოიზაცია გააკეთო. css() უტილიტა ხომ აბრუნებს ფუნქციას. ყოველ ჯერზე რომ არ გამოიძახო css ფუნქცია useMemo-ში უნდა ჩასვა

```js
const boxStyles = useMemo(() => css({...}), [...deps])
```

2022-07-19 09:32 UTC, ggogobera commented on src/components/reusables/Box.js
> +    display: display,
display: display-ს ნაცვლად უბრალოდ display რატომ არ არის? როგორც flex-ში გაქვს მოკლე სინტაქსით გაკეთებული? უნდა დაიცვა კონსისტენტურობა

2022-07-19 09:33 UTC, ggogobera commented
https://stitches.dev/docs/installation#import-and-use-it

2022-07-19 09:36 UTC, ggogobera commented on src/components/reusables/Input.js
ისე აქ კარგი იქნებოდა ბულეან ტიპის ვარიანტი რომ გაგვეკეთებინა. ანუ normal იქნებოდა დიფოლტად და fluid ბულეანს თუ მისცემდი მაშინ ფლუიდი გახდებოდა.

https://stitches.dev/docs/variants#boolean-variants

```js
styled('input', {
   width: '200px',
   
   variants: {
      fluid: {
         true: {...}
      }
   }
})
```

2022-07-19 11:08 UTC, BesoBerdzenishvili commented on src/components/reusables/Box.js
> +    display: display,
გოგა issue-ში წერია რომ Box-ში display: flex|inline-flex შემთხვევაში უნდა გამოიყენოთ JustifyContent, alignSelf, alignItems; 
DRY ხოარ გამომივა ესე რომ დავწერო?:
```variants: {
      display: {
        flex: {
          justifyContent,
          alignItems,
          alignSelf,
        },
        inlineFlex: {
          justifyContent,
          alignItems,
          alignSelf,
        },
      },
    }```
რადგან **ლოგიკური ან** არ გამოიყენება სტიჩებში (როგორც ვიცი)

2022-07-21 08:46 UTC, ggogobera commented on src/components/reusables/Box.js
> +    display: display,
DRY გამოვიდეს, მერე რა? :)

2022-07-21 08:52 UTC, ggogobera requested changes

2022-07-21 08:52 UTC, ggogobera commented on src/components/reusables/Button.js
> +          color: 'vlue',
typo: blue

2022-07-21 08:52 UTC, ggogobera commented on src/components/reusables/Input.js
> +  const StyledInput = styled('input', {
იგივე შეცდომა გქონდა წინა პროექტშიც.

ნუ აღწერ სტატიკურ კონსტანტებს (არა-დინამიური property-ზე არა-დამოკიდებული) კომპონენტში. დაგიწერე კიდეც ზუსტად როგორც უნდა გაგეკეთებინა.

ეს რაც ახლა გაქვს გაკეთებული ყოველ რე-რენდერზე გამოიწვევს სტილების ახლიდან შექმნას (under the hood სტილის ჰეშის შეცვლას) და გექნება ბაგი და პერფორმანს იშუ. ძალიან დიდი შეცდომაა

2022-07-21 08:52 UTC, ggogobera commented on src/components/reusables/Button.js
> +  })
ეს ყველაფერი ისე უნდა გააკეთო, როგორც StyledInput.

2022-07-21 08:52 UTC, ggogobera commented on src/components/reusables/Button.js
> +    <Component className={btnStyles({variant: variant, size: size})} {...restProps}>
შეცდომა 

n1: short სინტაქსს არ იყენებ
n2: btnStyles ფუნქცია არ იღებს არგუმენტებს და რატომ გადასცემ არ ვიცი. სადმე ნახე რომ იღებდეს არგუმენტებს?

2022-07-25 06:36 UTC, BesoBerdzenishvili commented on src/components/reusables/Button.js
> +    <Component className={btnStyles({variant: variant, size: size})} {...restProps}>
კონკრეტულად სადაა აქ მოკლე სინტაქსი გამოსაყენებელი?

2022-07-25 08:22 UTC, ggogobera commented on src/components/reusables/Button.js
> +    <Component className={btnStyles({variant: variant, size: size})} {...restProps}>
`{variant: variant, size: size}` → `{variant, size}`

2022-07-25 08:22 UTC, ggogobera commented on src/components/reusables/Button.js
> +    <Component className={btnStyles({variant: variant, size: size})} {...restProps}>
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#new_notations_in_ecmascript_2015

2022-07-25 13:50 UTC, ggogobera requested changes

2022-07-25 13:50 UTC, ggogobera commented on src/components/reusables/Button.js
> +const BtnStyles = styled('button', {
თუ StyledInput დავარქვით ინფუთს, StyledButton რატომ არ არის ეს? keep consistency

2022-07-25 13:50 UTC, ggogobera commented on src/components/reusables/Input.js
> +  return <StyledInput {...restProps} fluid={fluid} />
```js
export default function Input(props) {
   return <StyledInput {...props} />
}
```

რომ იყოს რა შეიცვლება? ხომ უკეთესია?

2022-07-25 16:40 UTC, BesoBerdzenishvili commented on src/components/reusables/Input.js
> +  return <StyledInput {...restProps} fluid={fluid} />
უფრო ლაკონური ნამდვილად არის, მაგრამ ფლუიდი აღარ მუშაობს მერე (ანუ width = 100% აღარ აძლევს ინპუტს). შენ ცადე ეგრე და იმუშავა?

2022-07-25 20:46 UTC, ggogobera commented on src/components/reusables/Input.js
> +  return <StyledInput {...restProps} fluid={fluid} />
კი ბატონი

<video src="https://user-images.githubusercontent.com/41262747/180870957-d94f4815-25c7-4550-b9c6-248124adf019.mov"></video>

2022-07-26 07:13 UTC, BesoBerdzenishvili commented on src/components/reusables/Input.js
> +  return <StyledInput {...restProps} fluid={fluid} />
კოდში როგორც გქონდა ისე გადავაკეთე ინპუტის კომპონენტი და იმუშავა

მერე ღილაკიც ეგრე გადავაკეთე

ანუ როგორც მივხვდი პროპებში რომ იყო განსაზღვრული ფლუიდი (და ვარიანტი, ღილაკში) ამიტომ ფლუიდის ვალუე პროპს მისდიოდა და არა სტაილედის ფუნქციას და რომ მოვაცილეთ პროპებიდან ფლუიდი მერე პირდაპირ სტაილედს მიუვიდა

2022-07-26 07:19 UTC, ggogobera commented on src/components/reusables/Input.js
> +  return <StyledInput {...restProps} fluid={fluid} />
ვერ მივხვდი.

შეგიძლია მანახო როგორ გეწერა, რომ არ მუშაობდა? და ფიდბექს მოგცემ რა იყო არასწორად. საინტერესოა

2022-07-26 12:04 UTC, ggogobera requested changes

2022-07-26 12:04 UTC, ggogobera commented on src/components/reusables/Button.js
> +export default function Button({as: Component = 'button', children, ...restProps}) {
აქ as პროპსს არ იყენებ, არაფერს აკეთებს პრაქტიკულად.

```js
export default function Button({ as: Component = 'button', ...props }) {
  const buttonStyles = useMemo(() => css({...}), [...])

  return <Component {...props} className={buttonStyles()} />;
```

ასე უნდა იყოს

2022-07-28 10:14 UTC, BesoBerdzenishvili commented on src/components/reusables/Input.js
> +  return <StyledInput {...restProps} fluid={fluid} />
```
export default function Input({fluid, ...restProps}) {
...
  return <StyledInput {...restProps} fluid={fluid} />
```
ინპუტში ეს გადავაკეთე ამად:
```
export default function Input(props) {
  return <StyledInput {...props} />
```

2022-07-28 10:49 UTC, BesoBerdzenishvili commented on src/components/reusables/Button.js
> +export default function Button({as: Component = 'button', children, ...restProps}) {
as პროპსი მოვხსენი, მაგრამ Button-ს ხომ styled-ს ვუკეთებთ და არა css-ს, css რატომ გიწერია კოდში?
და useMemo-ც რა საჭიროა? ეგ ხომ  Box-ში გამოვიყენეთ რადგან css ფუნქციის შიგნით ახდენდა რენდერს.

2022-07-28 11:21 UTC, ggogobera commented on src/components/reusables/Button.js
> +export default function Button({as: Component = 'button', children, ...restProps}) {
წინა რევიუებში მეწერა რამდენჯერმე, თუ კომპონენტი დინამიური არ არის, მხოლოდ მაშინ იყენებ styled-ს, სხვა შემთხვევაში css.

არ მახსოვდა რომ ღილაკი as პროპსს იღებდა. შენ ის გააკეთე ბრმად რაც მე დაგიწერე და as ფუნქციონალი გამოტოვე.

მოკლედ, going forward: სტატიკური-styled, სადაც styled-ს ვერ იყენებ css.

useMemo იმიტო გამოვიყენე რომ css-ზე გადავაწყე

2022-08-22 09:22 UTC, ggogobera approved these changes

2022-08-22 09:22 UTC, merged